import { createRouter, createWebHistory } from 'vue-router'
import HomeView from '../views/HomeView.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'home',
      component: HomeView,
    },
    {
      path: '/about',
      name: 'about',
      // route level code-splitting
      // this generates a separate chunk (About.[hash].js) for this route
      // which is lazy-loaded when the route is visited.
      component: () => import('../views/AboutView.vue'),
    },
    // autogenerated routes for modules
    {
      path: '/Administracion/ConfiguracionPlanes',
      name: 'ConfiguracionPlanes',
      component: () => import('../views/Administracion/ConfiguracionPlanes.vue'),
    },
    {
      path: '/Administracion/GestionInstituciones',
      name: 'GestionInstituciones',
      component: () => import('../views/Administracion/GestionInstituciones.vue'),
    },
    {
      path: '/Administracion/GestionUsuarios',
      name: 'GestionUsuarios',
      component: () => import('../views/Administracion/GestionUsuarios.vue'),
    },
    {
      path: '/Administracion/RespaldosIntegraciones',
      name: 'RespaldosIntegraciones',
      component: () => import('../views/Administracion/RespaldosIntegraciones.vue'),
    },
    {
      path: '/Administracion/SeguridadLogs',
      name: 'SeguridadLogs',
      component: () => import('../views/Administracion/SeguridadLogs.vue'),
    },
    {
      path: '/Dashboard/AdminSaaS',
      name: 'AdminSaaS',
      component: () => import('../views/Dashboard/AdminSaaS.vue'),
    },
    {
      path: '/Dashboard/Director',
      name: 'Director',
      component: () => import('../views/Dashboard/Director.vue'),
    },
    {
      path: '/Dashboard/Docente',
      name: 'Docente',
      component: () => import('../views/Dashboard/Docente.vue'),
    },
    { path: '/Dashboard/UTP', name: 'UTP', component: () => import('../views/Dashboard/UTP.vue') },
    {
      path: '/Evaluacion/AplicarEvaluacion',
      name: 'AplicarEvaluacion',
      component: () => import('../views/Evaluacion/AplicarEvaluacion.vue'),
    },
    {
      path: '/Evaluacion/BancoPreguntas',
      name: 'BancoPreguntas',
      component: () => import('../views/Evaluacion/BancoPreguntas.vue'),
    },
    {
      path: '/Evaluacion/CrearEvaluacion',
      name: 'CrearEvaluacion',
      component: () => import('../views/Evaluacion/CrearEvaluacion.vue'),
    },
    {
      path: '/Evaluacion/Especificaciones',
      name: 'Especificaciones',
      component: () => import('../views/Evaluacion/Especificaciones.vue'),
    },
    {
      path: '/Evaluacion/EvaluacionesEstandarizadas',
      name: 'EvaluacionesEstandarizadas',
      component: () => import('../views/Evaluacion/EvaluacionesEstandarizadas.vue'),
    },
    {
      path: '/Evaluacion/GuiasRemediales',
      name: 'GuiasRemediales',
      component: () => import('../views/Evaluacion/GuiasRemediales.vue'),
    },
    {
      path: '/Evaluacion/Resultados',
      name: 'Resultados',
      component: () => import('../views/Evaluacion/Resultados.vue'),
    },
    {
      path: '/Herramientas/Comunicacion',
      name: 'Comunicacion',
      component: () => import('../views/Herramientas/Comunicacion.vue'),
    },
    {
      path: '/Herramientas/PlanLector',
      name: 'PlanLector',
      component: () => import('../views/Herramientas/PlanLector.vue'),
    },
    {
      path: '/Herramientas/RecursosDidacticos',
      name: 'RecursosDidacticos',
      component: () => import('../views/Herramientas/RecursosDidacticos.vue'),
    },
    {
      path: '/InteligenciaEducativa/DiagnosticoInicial',
      name: 'DiagnosticoInicial',
      component: () => import('../views/InteligenciaEducativa/DiagnosticoInicial.vue'),
    },
    {
      path: '/InteligenciaEducativa/RecomendacionesIA',
      name: 'RecomendacionesIA',
      component: () => import('../views/InteligenciaEducativa/RecomendacionesIA.vue'),
    },
    {
      path: '/LibroClases/Asistencia',
      name: 'Asistencia',
      component: () => import('../views/LibroClases/Asistencia.vue'),
    },
    {
      path: '/LibroClases/Calificaciones',
      name: 'Calificaciones',
      component: () => import('../views/LibroClases/Calificaciones.vue'),
    },
    {
      path: '/LibroClases/Certificados',
      name: 'Certificados',
      component: () => import('../views/LibroClases/Certificados.vue'),
    },
    {
      path: '/LibroClases/FichaEstudiante',
      name: 'FichaEstudiante',
      component: () => import('../views/LibroClases/FichaEstudiante.vue'),
    },
    {
      path: '/LibroClases/Matricula',
      name: 'Matricula',
      component: () => import('../views/LibroClases/Matricula.vue'),
    },
    {
      path: '/LibroClases/RegistroActividades',
      name: 'RegistroActividades',
      component: () => import('../views/LibroClases/RegistroActividades.vue'),
    },
    {
      path: '/Planificacion/ActividadesClase',
      name: 'ActividadesClase',
      component: () => import('../views/Planificacion/ActividadesClase.vue'),
    },
    {
      path: '/Planificacion/PlanificacionAnual',
      name: 'PlanificacionAnual',
      component: () => import('../views/Planificacion/PlanificacionAnual.vue'),
    },
    {
      path: '/Planificacion/PlanificacionSemanal',
      name: 'PlanificacionSemanal',
      component: () => import('../views/Planificacion/PlanificacionSemanal.vue'),
    },
    {
      path: '/Planificacion/Unidades',
      name: 'Unidades',
      component: () => import('../views/Planificacion/Unidades.vue'),
    },
    {
      path: '/Reflexion/BitacoraDocente',
      name: 'BitacoraDocente',
      component: () => import('../views/Reflexion/BitacoraDocente.vue'),
    },
    {
      path: '/Reflexion/PanelPlanificacion',
      name: 'PanelPlanificacion',
      component: () => import('../views/Reflexion/PanelPlanificacion.vue'),
    },
    {
      path: '/Reflexion/PlanMejoramiento',
      name: 'PlanMejoramiento',
      component: () => import('../views/Reflexion/PlanMejoramiento.vue'),
    },
    {
      path: '/Suscripciones/Facturacion',
      name: 'Facturacion',
      component: () => import('../views/Suscripciones/Facturacion.vue'),
    },
    {
      path: '/Suscripciones/Pagos',
      name: 'Pagos',
      component: () => import('../views/Suscripciones/Pagos.vue'),
    },
    {
      path: '/Suscripciones/Planes',
      name: 'Planes',
      component: () => import('../views/Suscripciones/Planes.vue'),
    },
    {
      path: '/Suscripciones/RenovacionesExpiraciones',
      name: 'RenovacionesExpiraciones',
      component: () => import('../views/Suscripciones/RenovacionesExpiraciones.vue'),
    },
  ],
})

export default router
